### ISSUE TITLE
General maintenance

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-bbpress#1]
The plugin hasn't been updated in over 3 years. Let's give it a once over and check for issues, update the readme.txt, etc.

If we find any specific issues, or see room for any new features, we can open separate issues for those.

**Comment by nosegraze** [comment]
Things I found on first look:

- Add PHPDocs.
- Sanitize meta while saving.
- This method of passing in query args grosses me out: https://github.com/restrictcontentpro/rcp-bbpress/blob/master/includes/topic-functions.php#L93

**Comment by nosegraze** [comment]
PR: #3
