### ISSUE TITLE
Restricted topics still appear readable in RSS feed to unauthorized users

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-bbpress#9]

**Comment by misulicus** [comment]
The same user who reported the above just sent an update. The user profile link also show all the content posted in the forums BUT its just a matter of showing the post titles, the actual content is restricted when you try to open them.
Example: https://www.site.com/forums/users/ryan/topics/ will show all the topics posted even when some are restrcited.

He just wanted to mention it in case its not supposed to show them at all

**Comment by nosegraze** [comment]
I think this is the profile issue? https://github.com/restrictcontentpro/rcp-bbpress/issues/5

**Comment by misulicus** [comment]
Oh. I did not see that. Yeah that’s the one

**Comment by nosegraze** [comment]
PR: #13
